# Generated by Django 4.0.2 on 2022-02-04 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.CharField(max_length=1000)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
