# Generated by Django 4.0.2 on 2022-02-04 15:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.CharField(max_length=1000)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, default=0, max_digits=10), db_index=True, default=None, null=True, size=None)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('nationality', models.CharField(default=None, max_length=50, null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, null=True, size=None)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Homestay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=50, null=True), default=None, null=True, size=None)),
                ('location', models.CharField(default=None, max_length=50, null=True)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, default=0, max_digits=10), db_index=True, default=None, null=True, size=None)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, null=True, size=None)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.CharField(max_length=1000)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, default=0, max_digits=10), db_index=True, default=None, null=True, size=None)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('nationality', models.CharField(default=None, max_length=50, null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
