# Generated by Django 4.0.2 on 2022-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_alter_guide_first_name_alter_guide_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
